### ISSUE TITLE
Redis exception; nested exception is io.lettuce.core.RedisException: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer

### ISSUE THREAD

**Issue by gxl191911** [lettuce-io/lettuce-core#1027]
#### Environment
- Lettuce version(s): [5.0.5.RELEASE]
- Redis version: [spring-data-redis.2.0.11.RELEASE]

Hello, I have an exception when I use spring-boot-starter-data-redis:
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is io.lettuce.core.RedisException: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer] with root cause.
Is there any solution?

**Comment by mp911de** [comment]
There's nothing we can do from our side. This is a network issue, see https://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean.

**Comment by redwolf2019** [comment]
If connection was lost,why Lettuce did't try to reconnect to Redis ?

**Comment by zakaf** [comment]
i had the same problem and the problem was not in lettuce, but with my load balancer.
My load balancer was dropping tcp connection information between host and redis after certain idle time.
In my case i had two options.
1. Turn on keepalive in lettuce socket options and host OS needed to have valid tcp keep alive related values. https://www.tldp.org/HOWTO/html_single/TCP-Keepalive-HOWTO/
2. Set tcp-keepalive config in redis.conf to a shorter value. My load balancer's idle timeout was 120, so i set tcp-keepalive to 60 and it worked without problem

**Comment by ng-life** [comment]
> If connection was lost,why Lettuce did't try to reconnect to Redis ?

+1

**Comment by Scoty** [comment]
> If connection was lost,why Lettuce did't try to reconnect to Redis ?

+1
