### ISSUE TITLE
Getting all Hash by prefix

### ISSUE THREAD

**Issue by vaporizel** [lettuce-io/lettuce-core#1114]
I have a case to get all 300.000 redis hash inside live server and dump it into text file, so basically the hash prefix is "AKARAPACI*" so i want retrieve all hash beginning with AKARAPACI and dump into regular text file.

My questions is can lettuce gets all of these by prefix? when i read documents about hgetall and keyvaluestreaming it doesn't provide enough information to retrieve the hash by prefix.

**Comment by mp911de** [comment]
You need to fetch each key individually. You can issue a `SCAN <prefix>*`, inspect each returned key for `TYPE <key>` and if it's a hash, then you would issue a  `HGETALL` command.

These are't specific to Lettuce. What you've seen with Key/Value streaming is that results are streamed rather than aggregated into a `Map` which changes reduces memory requirements if you just write out key-values into a file or so.

**Comment by vaporizel** [comment]
Sorry, i'm totally new in this, how do i use scan command by prefix using lettuce in java? i know scan command of redis-cli but no idea about how to use it in letuce. btw thank you before

**Comment by mp911de** [comment]
Check out the [API documentation](https://lettuce.io/core/release/api/index.html) and the [reference docs](https://lettuce.io/core/release/reference/index.html) for examples.
