### ISSUE TITLE
Contradictory documentation for createBoundedObjectPool

### ISSUE THREAD

**Issue by mvh77** [lettuce-io/lettuce-core#1231]
Hi!

The Javadoc for [createBoundedObjectPool](https://github.com/lettuce-io/lettuce-core/blob/master/src/main/java/io/lettuce/core/support/AsyncConnectionPoolSupport.java#L98-L100) says that if wrapConnection is true one should call StatefulConnection#close(). Yet the documentation [here](https://lettuce.io/core/release/reference/index.html#connection-pooling.asynchronous.connection-pool-support) uses [createBoundedObjectPool](https://github.com/lettuce-io/lettuce-core/blob/master/src/main/java/io/lettuce/core/support/AsyncConnectionPoolSupport.java#L88-L91) (with wrapConnection=true) but calls pool.release(c) (which should be called with wrapConnection=false). Which one is correct?

#### Environment

- Lettuce version(s): 5.2.2.RELEASE
- Redis version: 5.0.7

**Comment by mp911de** [comment]
The documentation isn't contradictory but rather suggests the method of release. Wrapped connections can be released either by calling `close()` on the connection or by calling `release()` on the pool. The only thing that does not work is calling `close()` on a non-wrapped connection as that would close the connection instead of releasing it.

Happy to review a pull request to improve the docs if you have suggestions.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
