### ISSUE TITLE
Open up parts of the API

### ISSUE THREAD

**Issue by dontgitit** [lettuce-io/lettuce-core#1311]
## Feature Request

I'm working on a Scala wrapper of your library that brings two key features:
1.) easier Scala interoperability
2.) thread-safety across transactions

In order to achieve the latter, whenever someone calls `multi`, I'm essentially doing something like
1.) return a new object that from the outside looks like it's a redis client, but is actually a wrapper around the current client
2.) all methods (other than `exec`) that get called, create a `Command` and push it to a queue
3.) once `exec` is called: take out a shared lock, send the server a multi, followed by all the commands in the queue, followed by exec, and release the lock
4.) this wrapper may not be used again

I implemented it and it all works just fine, but I had to do something ugly: for a few classes, I had to declare them inside of a package `io.lettuce.core` so that I could access some internals. This included:
a.) `CommandArgs.singularArguments`, in order to access all the keys in a command. Used to find the slot/underlying connection to use if running in cluster mode.
b.) `BaseRedisAsyncCommands.dispatch`, in order to dispatch the queued commands
c.) `RedisCommandBuilder`, to create `Command`s to dispatch

Is my goal to create a thread-safe transactional API reasonable? Would you go about it different? Would you consider opening up the visibility of some of these APIs, or do you have any suggestions about how I could implement it differently?

#### Is your feature request related to a problem? Please describe

My project runs in a highly parallel environment, and the lack of thread safety in the `multi` API is very cumbersome.

#### Describe the solution you'd like

Opening up parts of the API to make extending it easier.

#### Describe alternatives you've considered

Haven't been able to think of much.

#### Teachability, Documentation, Adoption, Migration Strategy

This change wouldn't really have much impact on existing users.

**Comment by mp911de** [comment]
Great to hear you're bringing Lettuce to the Scala community and hanks for reaching out. I also wondered whether it makes sense to open up a few bits. My comments are inline:

> a.) CommandArgs.singularArguments, in order to access all the keys in a command. Used to find the slot/underlying connection to use if running in cluster mode.

We can do that. There's already `CommandArgsAccessor` and `CommandArgs.getFirstEncodedKey()` that are used by `ClusterDistributionChannelWriter` for cluster routing.

> b.) BaseRedisAsyncCommands.dispatch, in order to dispatch the queued commands

That API is already public as the type is an interface.

> c.) RedisCommandBuilder, to create Commands to dispatch

I'm not keep opening up `RedisCommandBuilder` as it is internal API. By exposing it, we sort-of promise to not break it which we cannot guarantee.

Instead, you could do some trickery with `AbstractRedisAsyncCommands` where you put in a stubbed `StatefulConnection` that does a pass-thru for `dispatch(…)` (leaving all other methods unimplemented). You get in return `AsyncCommand` instances which you can either submit directly or unwrap for further command composition.

In general, I like the idea of returning a transaction handle that allows the invocation of transactional commands without worrying about concurrent/interleaving commands.

Let me know what you think about the above suggestions. We can also continue the discussion over a pull request that shows how you would like to change the Lettuce API since you know the requirements best.

**Comment by dontgitit** [comment]
> In general, I like the idea of returning a transaction handle that allows the invocation of transactional commands without worrying about concurrent/interleaving commands.

OK, great to hear it makes sense! Would you ever considering implementing that, or some other solution, in your library that would make transactional commands thread safe?

> There's already CommandArgsAccessor and CommandArgs.getFirstEncodedKey() that are used by ClusterDistributionChannelWriter for cluster routing.

What if the command has multiple keys, and some of the keys map to a different node? In my code I basically checked all the keys and threw an exception immediately if they belong to different nodes (when running a transaction). Is that unnecessary?

> I'm not keen on opening up RedisCommandBuilder as it is an internal API. By exposing it, we sort-of promise to not break it which we cannot guarantee.

That's fair I guess... btw I noticed `CommandArgsAccessor` has a similar note, `This class is part of the internal API and may change without further notice.`

> Instead, you could do some trickery with AbstractRedisAsyncCommands

Thanks for the suggestion! I tried it out and it worked! It was a little nasty since everything in `AbstractRedisAsyncCommands` returns a `RedisFuture` and I had to explicitly cast it to `AsyncCommand` so I could actually `dispatch` it with the real client later on... but other than that it worked out fine!

P.S. In my implementation of thread-safe multi, I created a ReadWriteLock per underlying connection. I take out a read lock against it when executing a command outside of a transaction. When processing a transaction, I acquire a write lock instead. This way I can have any number of non-transactional commands running in parallel as long as there is no transaction in flight. However, it essentially introduces some blocking if there is a transaction in place... 

Looking at the `StatefulConnection` API as part of your suggestion, it seems you already have a `dispatch(Collection[Command] commands)`. Per the docs... since it dispatches the commands in a single write, it's essentially thread safe if I supply `Collection(multi, command1, command2, etc, exec)`, and I could get rid of the locking...

However, `BaseRedisAsyncCommands` doesn't provide a `dispatch` taking multiple commands. Can I just do something like `AbstractRedisAsyncCommands.getConnection().dispatch(commands)`, or would that break something by bypassing the client and going directly to the connection?

**Comment by mp911de** [comment]
> Would you ever considering implementing that, or some other solution, in your library that would make transactional commands thread safe?

There's no real motivation on our side. There are however plenty of reasons why the current arrangement works:

* Someone wanting to issue a `MULTI` statement and incrementally trigger commands is free to do so and we do not impose any limitations beside concurrency onto users
* Returning a state object from `MULTI` would require a different API for transactional use. While this can be fine for applications, frameworks (such as Spring Data) typically see a different API difficult as it causes more code paths
* Issuing a transactional stack can cause memory exhaustion/allocation issues. Submitting a bulk of commands guarantees atomicity because the I/O thread can handle one I/O task at a time and so a bulk is guaranteed to be sent atomically. The flip side is, that a collection of commands is written onto a single buffer (see `CommandEncoder`). We've seen already reports where sending a single batch (e.g. after a reconnect) caused memory allocation failures.

> I created a ReadWriteLock per underlying connection

The lock bit caught my attention. Lettuce aims at being non-blocking. Introducing synchronization should be handled with care and ideally, use non-blocking synchronization (such as `AtomicBoolean.compareAndSet(…)` guards). Non-blocking synchronization doubles down on already complex synchronization issues but it's worth the effort to ensure scalability.

> `dispatch(Collection)` on `BaseRedisAsyncCommands`

There's no `dispatch` method on the Async API accepting a collection because we would have to return a collection of futures which is a bit weird when looking at it from a programming model perspective. A collection of futures doesn't seem right. You can use the method on the actual connection (that's also what the async API does).
On the connection level, we don't have that strong affinity to futures, therefore we return a collection of written commands which might be futures, yet they aren't forced into futures.

**Comment by dontgitit** [comment]
Hi, sorry about my delay in responding, I got distracted by other things.

I think I may have found a bug. I tried implementing your suggestion (of calling `Connection.dispatch(Collection commands)` for the entire batch rather than locking, and then calling `dispatch` for each individual command). However, once I removed the locks that I had in my code, my tests started failing. I'm **mostly** convinced my code is correct, so I started looking at the library code. 

I think the culprits might be `write(Collection<? extends RedisCommand<K, V, ?>> commands)` and `writeToChannelAndFlush(Collection<? extends RedisCommand<?, ?, ?>> commands)` in `DefaultEndpoint`. The former basically does `sharedLock.incrementWriters()` and then invokes `writeToChannelAndFlush`. However, that writes ***each command separately*** rather than in a single write?

```java
for (RedisCommand<?, ?, ?> command : commands) {
  channelWrite(command);
}
channelFlush();
```

Is it possible that another thread can sneak another `channelWrite` in there? That would be consistent with the behavior I'm observing. I took a look at the `sharedLock` (I think it's there to prevent this exact thing?) but I'm not sure I understand how it works. Should the code be calling `sharedLock.doExclusive` rather than `sharedLock.incrementWriters` here? Based on my understanding, `sharedLock.incrementWriters` doesn't seem to prevent other writers from adding commands to the channel at the same time (which is totally fine outside of a transaction, but disastrous otherwise...)

**Comment by dontgitit** [comment]
P.S. Looks like `CommandEndcoder` is already able to encode a `Collection` of commands, so maybe `DefaultEndpoint` should just channel write the entire collection in a single operation, rather than writing each command individually?

**Comment by mp911de** [comment]
We wrote previously (2 years ago or so) all commands as batch until someone reported timeout issues with batching (see #729).

Feel free to check out the diff 87babad2930a20001ec094309d7440007c4c65ff that changed the command write behavior. Individual writes can indeed cause command interleaving and I can see that this behavior will break transactional atomicity.

**Comment by dontgitit** [comment]
Ah yes - based on that PR, the old behavior is exactly what I was suggesting :(
I tried reading through #725 / #726 / #729 but I'm not familiar with netty nor lettuce so it went a little over my head to be honest. 
Since there is no method that writes multiple commands at once anymore... are there any other workarounds for me? Obviously I can continue to use locks (but I'd like to remove them), or I can make a new connection for each transaction (super inefficient, though I could make it better with a pool or something). 

Since the issue that you originally fixed is only a problem for exceptionally large batches of commands, is there any chance you'd be willing to add a `dispatch(Collection commands, boolean atomically)` to `StatefulConnection`, and thread it all the way down to `DefaultEndpoint` where it does the old `channel.write(commands)` behavior if `atomically == true`? Or maybe there's some other way to incorporate an optional flag that'll allow the transactional use case?

**Comment by mp911de** [comment]
To some degree, non-atomic writing is compensating for large batches. I would love to see the atomic batch write to come back as it is more efficient (less TCP packages, less flushes, less additional orchestration) but it requires a larger chunk of memory.

I was thinking about something that we introduce a cap (say 1000, maybe controlled through a system property). If a batch exceeds that limit, then we issue a warning. Additionally, we need to add a partitioning mechanism when we replay commands upon reconnect. Then it would be a bit safer to handle atomic chunks. 

Whether a chunk is transactional or not it doesn't really change anything about a potential timeout impact or the memory that is required.

**Comment by dontgitit** [comment]
Would it be easier to add an overload that just uses the old behavior?

**Comment by mp911de** [comment]
> Would it be easier to add an overload that just uses the old behavior?

Then we re-introduce the error-prone behavior without helping users to understand why they potentially run into issues.

https://github.com/lettuce-io/lettuce-core/issues/1311#issuecomment-660942403 isn't really saying that I'm avoiding complexity, it's more outlining what we can/should do.

**Comment by mp911de** [comment]
Since there's no movement and this ticket isn't actionable right now, closing it until we get more insights or requests for this matter.

**Comment by dontgitit** [comment]
fair enough! FWIW we've been using the version with the ReadWriteLock and it's been working well enough
