### ISSUE TITLE
Consider upgrade to io.netty 5+ since Synopsys BlackDuck reports medium vulnerability in io.netty 4.*

### ISSUE THREAD

**Issue by nikran** [lettuce-io/lettuce-core#1366]
#### Is your feature request related to a problem? Please describe

Synopsys BlackDuck reports a medium vulnerability in io.netty 4.* 
Netty does not verify the hostname when establishing connections with clients which allows a potential attacker to forge a certificate and pose as the intended peer. An attacker can leverage this flaw by crafting a cryptographically valid certificate which will be accepted by Netty due to missing hostname verification.

SInce BlackDuck is a widely used tool for open source security and having medium security vulnerability in lettuce-core dependency could push some people not to use or replace lettuce library

#### Describe the solution you'd like

Please consider upgrade to io.netty 5+

**Comment by mp911de** [comment]
Can you provide a bit more context and the version number? Netty 4 is a widely used library with a version range between 4.0 to 4.1.51 of which 4.0 was released in 2013 and 4.1.51 last month.

Since Lettuce is configuring hostname verification itself, the mentioned vulnerability doesn't apply.

We currently don't plan yet to upgrade to netty 5 since netty 5 is still in development.

**Comment by nikran** [comment]
A vulnerability exists even in the latest version
According to netty Eng team issue will be solved in final 5 version 
You could find more information here
https://github.com/netty/netty/issues/10362

**Comment by mp911de** [comment]
As per comment in the linked ticket, Lettuce is enabling SSL verification by default, the mentioned vulnerability doesn't apply.

We're closing this ticket since we cannot do here anything.

**Comment by nikran** [comment]
It is enabled by default from Netty 5, but in Netty 4.*.* is disabled by default
