### ISSUE TITLE
Add support for CommandListeners

### ISSUE THREAD

**Issue by sokomishalov** [lettuce-io/lettuce-core#1382]
It would be great to have a handler API of executing commands.
I think there are a lot of possible use cases.

For example, I want to log all executing commands (input and output).
Current logging is not very human-friendly, actually :)
My temporary solution looks like this, but I don't think it's quite elegant:
https://gist.github.com/SokoMishaLov/207c8082594685daa44cbd60127960a8

Thanks!

**Comment by mp911de** [comment]
Thanks. We could introduce an API along the lines of:

```
public interface CommandListener {
    /**
     * Listener for command started events.
     *
     * @param event the event
     */
    default void commandStarted(CommandStartedEvent event) {
    }

    /**
     * Listener for command completed events
     *
     * @param event the event
     */
    default void commandSucceeded(CommandSucceededEvent event) {
    }

    /**
     * Listener for command failure events
     *
     * @param event the event
     */
    default void commandFailed(CommandFailedEvent event) {
    }

}
```

that get notified upon command events from `CommandHandler`. Since support for metrics and tracing are configured on `ClientResources`, it makes sense to put command listeners there, too.

Command events would typically hold the command type, arguments and the output (for success) and the error/exception for the failed case.

We also need to consider that commands may get canceled (i.e. connection closed) from the endpoint implementation which would ultimately call `commandFailed`.

**Comment by SokoMishaLov** [comment]
That's almost exactly what I expected to see.
I think the command event should also hold context/correlation/whatever to correlate events.

**Comment by mp911de** [comment]
Do you have an example of how you would like to attach data to a command or how the API for the context should look like?

**Comment by SokoMishaLov** [comment]
I think it should look like typical key-value storage.

https://github.com/r2dbc/r2dbc-proxy/blob/main/src/main/java/io/r2dbc/proxy/core/QueryExecutionInfo.java#L180

**Comment by FitBBC** [comment]
No place to configure CommandListener found in ClientResources

**Comment by mp911de** [comment]
Command listeners are configured via `RedisClient`/`RedisClusterClient`
