### ISSUE TITLE
The setTimeout method is invalid for StatefulRedisClusterConnection

### ISSUE THREAD

**Issue by frankylyc334** [lettuce-io/lettuce-core#1383]
## Bug Report
The `setTimeout` method is invalid for `StatefulRedisClusterConnection`.
First we check the `connectClusterAsync` method in `RedisClusterClient.java`

```
        RedisChannelWriter writer = endpoint;

        if (CommandExpiryWriter.isSupported(clientOptions)) {
            writer = new CommandExpiryWriter(writer, clientOptions, clientResources);
        }

        ClusterDistributionChannelWriter clusterWriter = new ClusterDistributionChannelWriter(clientOptions, writer,
                clusterTopologyRefreshScheduler);
```

In this code, we can know that the real writer for `StatefulRedisClusterConnection` (generated by `RedisClusterClient.connect()`) is a `ClusterDistributionChannelWriter`

Then we check the `setTimeout` method for `StatefulRedisClusterConnection`, the implement of `setTimeout` method is in `StatefulRedisClusterConnectionImpl.java`, 
```
public class StatefulRedisClusterConnectionImpl<K, V> extends RedisChannelHandler<K, V>
        implements StatefulRedisClusterConnection<K, V>
```
and we can find the `setTimeout` method in `RedisChannelHandler.java`

```
public void setTimeout(Duration timeout) {

        LettuceAssert.notNull(timeout, "Timeout duration must not be null");
        LettuceAssert.isTrue(!timeout.isNegative(), "Timeout duration must be greater or equal to zero");

        this.timeout = timeout;

        if (channelWriter instanceof CommandExpiryWriter) {
            ((CommandExpiryWriter) channelWriter).setTimeout(timeout);
        }
}
```

The timeout will be set for the `channelWriter` only if it is a `CommandExpiryWriter`. But according to our previous analysis, the `channelWriter` for `StatefulRedisClusterConnection` is a `ClusterDistributionChannelWriter`. So the `setTimeout` method won't work for RedisCluster

#### Environment

- Lettuce version(s): This problem is in both 5.2.0.RELEASE & 5.3.2.RELEASE

#### Possible Solution

We can add additional judgement for `ClusterDistributionChannelWriter` in `setTimeout` method

**Comment by mp911de** [comment]
Lettuce applied until version 5 timeouts only to the synchronous command API. Commands issued through the async and reactive APIs didn't time out. This behavior is rooted in the protocol definition. There's no way to cancel a running command with the Redis protocol.

In newer versions, we added timeout behavior on a global level to at least signal to callers that a command has timed out. Global timeouts are handled by `CommandExpiryWriter` and that's why the code is as it is now. With Lettuce 5.1, `TimeoutOptions` was introduced which enables global timeouts by default.

If you disable timeouts via `TimeoutOptions`, then `setTimeout` on the connection applies only to the synchronous command interface.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please feel free to leave a comment and we will re-open the issue.
