### ISSUE TITLE
RedisClusterClient would create a new connection for the command: COMMANDS

### ISSUE THREAD

**Issue by StillerRen** [lettuce-io/lettuce-core#1392]
When create the StatefulRedisClusterConnection object, lettuce would send the command: COMMANDS to the redis cluster and get the result to make sure which commands are available:
![image](https://user-images.githubusercontent.com/35724820/90306623-b1d97000-df01-11ea-87d9-784a8be9d17d.png)
but I find that lettuce would create a new connection for the command: COMMANDS, and use the other connection to do the other  commands:
![image](https://user-images.githubusercontent.com/35724820/90306655-0977db80-df02-11ea-8575-2046fa1fc7d3.png)
when I create a StatefulRedisClusterConnection  object and send the set command, the result of "client list" has two client, one is COMMANDS and the other one is SET, it means the client create two connections, but I think these two command should use the same connetion.

ps: I sent the SET command by the ASYNC command

the lettuce version: 5.2.0

**Comment by mp911de** [comment]
This is by design. Lettuce keeps a default connection to issue commands that aren't associated with a key (`PING`, `INFO`, `PUBLISH`). The [reference documentation](https://github.com/lettuce-io/lettuce-core/wiki/Redis-Cluster#connection-count-for-a-redis-cluster-connection-object) explains how cluster connections work.
