### ISSUE TITLE
Command queueing during redis outage doesn't seem to work

### ISSUE THREAD

**Issue by tcve** [lettuce-io/lettuce-core#1395]
## Bug Report

I've read the wiki and scoured the internet without finding an answer this. I'm sincerely hoping I've missed something obvious, or that my expectation of how this is meant to work is wrong.

#### Current Behavior

Setup: I have a bare bones spring boot web app (using spring data, as recommended by the lettuce docs) with a single endpoint to cache a simple key:value. I have a local redis server running. I am able to successfully use lettuce to cache things through the spring app to my local redis. All of my lettuce settings are left as default.

Expected behavior: When I stop my local redis server, I expect lettuce to attempt auto-reconnection and subsequent calls to my spring endpoint to queue the resulting cache commands. Upon starting the local redis server, I expect lettuce to reconnect and the queued commands to be executed and the cache updated.

Actual behavior: After stopping my local redis server, I see lettuce attempting to auto-reconnect. When I hit my endpoint, it hangs for a minute and then lettuce throws a RedisCommandTimeoutException. When I restart my redis server, I see lettuce successfully reconnect, but the command that tried to run while redis was down does NOT get executed, nor are there any logs suggesting any sort of queuing happening.

#### Input Code

Configuration code:
```
@Configuration
public class RedisConfig {
    @Bean
    public LettuceConnectionFactory redisConnectionFactory() {
        return new LettuceConnectionFactory(new RedisStandaloneConfiguration("localhost", 6379));
    }

    @Bean
    public StringRedisTemplate redisTemplate() {
        return new StringRedisTemplate(redisConnectionFactory());
    }
}
```

The single endpoint:
```
@PutMapping("/cache")
public void cache(@RequestParam(value = "key") String key, @RequestParam(value = "value") String value) {
    redisTemplate.opsForValue().set(key, value);
}
```

#### Environment

- Lettuce version(s): 5.3.3.RELEASE
- Redis version: 6.0.3
- Spring Data Redis version: 2.3.3.RELEASE

**Comment by mp911de** [comment]
> I expect lettuce to attempt auto-reconnection and subsequent calls to my spring endpoint to queue the resulting cache commands

That's exactly what happens. Any Redis-based health check queues also the command that is being used for the health check. Since the command doesn't complete, you see a hanging health check for 60 seconds by default. 

You can change the behavior by either reducing the timeout or by telling Lettuce to reject commands while the connection is disconnected. See `ClientOptions` in the docs for further reference.

**Comment by tcve** [comment]
Well that's just the problem. No subsequent calls are being queued and then applied upon re-connection. I have read the docs forward and backward to see if I'm doing something wrong, but from everything I've read it seems that the default options should produce the desired behavior here.

Why was this issue closed? :(

**Comment by mp911de** [comment]
Because things work as expected:

> After stopping my local redis server, I see lettuce attempting to auto-reconnect. When I hit my endpoint, it hangs for a minute and then lettuce throws a RedisCommandTimeoutException. When I restart my redis server, I see lettuce successfully reconnect, but the command that tried to run while redis was down does NOT get executed, nor are there any logs suggesting any sort of queuing happening.

When commands time out because the Redis connection is interrupted, then the commands are completed with a `TimeoutException`. Completed commands aren't re-queued anymore.

If the connection gets restored before the commands time out, then the commands get re-applied once the connection is restored. The documentation basically states the same at the [end of chapter 4.2](https://lettuce.io/core/release/reference/index.html#basic-usage).

> Redis connections are designed to be long-lived and thread-safe, and if the connection is lost will reconnect until close() is called. Pending commands that have not timed out will be (re)sent after successful reconnection.

I closed the ticket under the assumption that the previous comment explained that behavior. I apologize if that was not the case. Please let me know if you need further assistance on this ticket.

**Comment by tcve** [comment]
Ahhh, okay. I had a feeling I was misunderstanding something. I didn't realize that redis has to come back up before the call timesout in order to have the redis command re-applied. Thank you!
