### ISSUE TITLE
I encountered a problem using lettuce client  in  High Concurrency  Service

### ISSUE THREAD

**Issue by chengjiafeng** [lettuce-io/lettuce-core#1599]
We have used  lettuce client  in  High Concurrency  Service。  When I used  “connection.async().get“，I  found many blocking threads in  High Concurrency  Service。Because of company policy，I cannot  upload image 。The blocking position is as follows：

connection.async().get(cacheKey.getBytes())---》 this.connection.dispatch(asyncCommand)---》 this.doWrite(command)---》 ((AsyncClusterConnectionProvider)this.clusterConnectionProvider).getConnectionAsync(intent, hash)---》intent == Intent.READ && this.readFrom != null && this.readFrom != ReadFrom.MASTER ? this.getReadConnection(slot) : this.getWriteConnection(slot).toCompletableFuture()---》synchronized(this.stateLock) {
            writer = this.writers[slot];
        }
 
Can't use asynchronous （connection.async().get） in  High Concurrency  Service ？

**Comment by mp911de** [comment]
Using the async API, you should not (must not) call `Future.get(…)` methods, otherwise you will block the EventLoop thread.

Internally, we use `synchronized` to enforce Java memory model visibility constraints. The activity in `synchronized` blocks performs purely computational instructions, typically variable/field assignments.

Is there anything else to help with this ticket?

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
