### ISSUE TITLE
Two Suggestions for Lettuce Documentation

### ISSUE THREAD

**Issue by cjs1992-github** [lettuce-io/lettuce-core#1840]
Hello, I have a few small questions for you. Please pay attention to them:
1. I read the developer guide you provided carefully and find that this guide provides a copy of Eclipse code specifications. Can I also provide a copy of the formatting requirements of IntelliJ IDEA?
2. I read a lot of documents on github and looked at many websites. I found that no place can provide the software architecture diagram of lettuce. This is not good for us to understand lettuce code. Can you provide such documents officially?
Thank you very much, if you reply.

**Comment by mp911de** [comment]
IntelliJ formats code slightly different than the Eclipse code formatter. We recommend installing the Eclipse formatter plugin for IntelliJ to keep a consistent code format.

Check out https://github.com/lettuce-io/lettuce-core/wiki/Connection-Internals for further details. Since this project is open source, you're welcome to contribute an architecture description document.

**Comment by cjs1992-github** [comment]
OK, thank you very much. I'll read the code carefully and provide some documentation as much as I can to contribute to the community.
