### ISSUE TITLE
How to force eager initialization for connections that are created lazily

### ISSUE THREAD

**Issue by ExploreNcrack** [lettuce-io/lettuce-core#2097]
How can we force eager initialization or configure the connection pooling or cluster mode client to ensure Pre-initialization on Startup? Is there a way to do that if I am not using Spring framework? Since we want to avoid long timeout on request thread for connections that are created lazily.

**Comment by mp911de** [comment]
When using a connection pool, you can pre-allocate all connections through the config. Through `ConnectionPoolSupport`, you typically provide a `Supplier` as factory method to create a connection. Using Redis Cluster you can use the Node Selection API (`connection.sync().all().commands().ping()`) to issue a command to all known nodes. That should move a significant part of the initialization time towards the application startup so that your first request duration (after the server is available) improves.

**Comment by ExploreNcrack** [comment]
Thanks for rapid response!
