### ISSUE TITLE
Client-side caching clarifications

### ISSUE THREAD

**Issue by sebarys** [lettuce-io/lettuce-core#2100]
Hello

I see that Lettuce support client side caching https://github.com/lettuce-io/lettuce-core/issues/1281 - it is great, thanks for your effort to implement it :) 

As I couldn't find more examples than in mentioned above ticket I have two questions:
- what is client side cache behaviour on Redis connection drop? I would like to keep high consistency so preferred would be to flush cache on connection drop. Is it possible to configure in such way (if it is not default behaviour)?
- is it possible to set any TTL for client side cache entries? I know that protocol should propagate invalidation signals, anyway I would like to invalidate cache entires after some long TTL (few hours). Is it sth that I can configure or it is sth that I would need implement externally?

Thanks for answers in advance!

Regards

**Comment by dkrcharlie** [comment]
hi Sebarys,

I got the same requirement to set TTL for client cached items. And I found a way to do that as below:

1. Write your own cache accessor by implements interface "io.lettuce.core.support.caching.CacheAccessor". 
2. Use Guava or Caffeine cache to implements the methods "public V get(K key)"....., you need to initial Guava or Caffeine cache  in contructor like:
    public CaffeineCacheMap() {
        this.cache = Caffeine.newBuilder().
                expireAfterWrite(clientSideCacheExpireTimeMinutes, TimeUnit.MINUTES).
                maximumSize(clientSideCacheMaxNumber).
                build();
    }

       @Override
    public V get(K key) {
        debugLogger.log(CLASS_NAME,"get(key)", "get cache with key [" + key + "]");
        return cache.getIfPresent(key);
    }

    @Override
    public void put(K key, V value) {
        debugLogger.log(CLASS_NAME, "put(key,value)", "put cache with key ["
                + key + "] and value [******]");
        cache.put(key,value);
    }

    @Override
    public void evict(K key) {
        debugLogger.log(CLASS_NAME,"evict(key)", "remove cache for key [" + key + "]");
        cache.invalidate(key);
    }
3. put your own CacheAccessor as parameter when trying to enable client-caching for Luttuce StatefulRedisConnection. like:
                lettuceClient = (LettuceClient) GlobalRedisClientFactory.getClient();
            StatefulRedisConnection<String, String> redisConnection = lettuceClient.unwrap();
            frontend = ClientSideCaching.enable(cacheMap, redisConnection,
                    TrackingArgs.Builder.enabled());
the "cacheMap" is an instance of your own implemented CacheAccessor.

**But still, we still need to find a way to clean caches when "reconnection" happen since reconnection will make redis caching tracing not working anymore.**

**Comment by mp911de** [comment]
Yep.

**Comment by Su57** [comment]
> You can register a connection listener with the Redis Client to react to connect/disconnect events and issue commands after connecting.

could you give some code examples here ? i work with spring boot and can not find a solution :(
