### ISSUE TITLE
Is it safe to use Load Balancer endpoint as the redis cluster client initial seed endpoint?

### ISSUE THREAD

**Issue by ExploreNcrack** [lettuce-io/lettuce-core#2106]
**use case**:
- redis cluster client

**config**:
- passing the Load Balancer endpoint as the initial seed node endpoint to create the redis cluster client

Load Balancer in this case can direct request to any one of the healthy node in redis cluster

**concern**:
When seed node is used for getting the initial cluster topology, would it consider the load balancer endpoint redisURI as the node connection for a specific partition and use that load balancer connection for executing the key (related) commands? Just want to confirm @mp911de since if that is the case, it will cause problems as the request going through load balancer can end up at a different node every time.
If we cannot use load balancer endpoint as the seed endpoint, is there a way to configure the redis cluster client to leverage the  load balancer endpoint for cluster topology discovery (cluster nodes)? Since with load balancer, the client can always get a topology back from a healthy node

**Comment by mp911de** [comment]
It is fine. In fact, Microsoft Azure Redis is using this approach letting the main DNS name point to a load balancer that backs its connection with an active node in the Redis cluster. 

I think that this is a fail-safe approach that comes with a reduced need for maintenance because DNS names for Load Balancers change less often than the cluster topology. Please keep in mind that the default connection (the one that connects to the first node of the cluster) is used for key-less commands. Routing of commands with a key requires additional connections even if the default connection could already serve a key.
