### ISSUE TITLE
Using shared connection is slower with larger values

### ISSUE THREAD

**Issue by bryanck** [lettuce-io/lettuce-core#2298]
## Bug Report

The Lettuce docs generally advise using a shared connection unless using blocking operations or transactions. However, in our production system, which caches larger values (>100KB), we noticed using a connection pool is faster with fewer latency spikes than using a shared connection.

Here is a simple project that roughly mimics our application load to demonstrate these findings: 
https://github.com/bryanck/bkredis

With smaller values, using the shared connection is faster, but when values reach a certain size, using a connection pool is faster.

#### Environment

- Lettuce version: 6.2.2.RELEASE
- Redis version: 7.0.7

#### Possible Solution

Ultimately we switched to a different client that uses connection pooling. An alternative would be to configure Lettuce to use a connection pool.

**Comment by bryanck** [comment]
This seems to be platform dependent so I'm going to close this until I gather more information. Thanks!

**Comment by mp911de** [comment]
There's something to consider: Using large, non-binary values (e.g. `String` or Jackson serialization) introduces load onto the CPU. With netty's threading model, each connection is associated with a `Thread`. If serialization takes a considerable amount of time, then connection pooling might be beneficial as it allows the utilization of multiple threads. 

A single-connection approach would not utilize the available (remaining) CPU capacity for serialization because of the single-thread affinity.
