### ISSUE TITLE
RedisURI cannot resolve sentinelPassword 

### ISSUE THREAD

**Issue by mengshaoyu** [lettuce-io/lettuce-core#2327]
My redis sentinel :  
redis-sentinel://[password]@[ip1]:[port1],[ip2]:[port2],[ip3]:[port3]/?sentinelPassword=xxxx&sentinelMasterId=aaaaa

but in class : io/lettuce/core/RedisURI.java#buildRedisUriFromUri  cannot resolve sentinelPassword

**Comment by mp911de** [comment]
The `?sentinelPassword=…` query parameter isn't supported. For proper support, we would need also the user name. Query parameters have the issue that they are not masked in the `toString` representation and impose a security concern.

Generally speaking, it is better to use `RedisURI` objects instead of serializing security-relevant objects as `String`. I'm not convinced that adding those two parameters is a good idea from a security and maintenance perspective.
