### ISSUE TITLE
brpop when timeout is set 0 issue

### ISSUE THREAD

**Issue by giridharkannan** [lettuce-io/lettuce-core#2354]
#### Current Behavior

When blocking indefinitely by specifying 0 for timeout, after the first REDIS max timeout (1 minute), brpop stops receiving messages even though REDIS sends those to the client.

#### Reason for the current behaviour

Old BRPOP command is not cleared in CommandHandler.java's stack field. This results in always notifying the old command instead of the present

#### Expected behavior/code

Must receive messages as we get even after first REDIS timeout (1 minute default timeout)

#### Environment

- Lettuce version(s): 6.1.10.RELEASE
- Redis version: 7.0.8\

**Comment by mp911de** [comment]
Command timeouts are client-side only for commands that have been sent to Redis. Redis does not reply with any command responses unless the blocking command has been processed. 

Not sure what you're asking for.

**Comment by giridharkannan** [comment]
What you say is true. Seems there is an internal max timeout of 1 minute at lettuce, post that, if the REDIS responds to BRPOP, we will not receive that message.

To reproduce the issue, call brpop(0, "key") 
wait for 1 minute and after that, try responding to brpop via lpush and you will not get that response

**Comment by mp911de** [comment]
That's all by design and since there's no way to retract a sent command from Redis (or cancel in-flight commands), there's nothing we can do here. However, with `TimeoutOptions` (via `ClientOptions`) you could provide a different command timeout to wait longer for blocking commands. See `TimeoutSource` for further details.

**Comment by giridharkannan** [comment]
I am finding it difficult to explain the issue in a simple term, so am sharing an test code link and also wireshark dump

https://github.com/giridharkannan/lettuce-blpop-issue/blob/main/src/main/java/LettuceTest.java

[redis_blpop_issue.zip](https://github.com/lettuce-io/lettuce-core/files/11271031/redis_blpop_issue.zip)

**Comment by mp911de** [comment]
Thanks for the reproducer. The code behaves as expected:

Your code doesn't receive the first message because the first `BRPOP` fails with a timeout. Still, Redis eventually responds to the command that has timed out. But because the command has failed on the client side, you can no longer consume the response.

```
127.0.0.1:6379> monitor
OK
1681899059.835379 [0 127.0.0.1:64651] "HELLO" "3"
1681899059.835504 [0 127.0.0.1:64652] "HELLO" "3"
1681899059.855885 [0 127.0.0.1:64651] "BRPOP" "test_queue" "0" <-- this times out
1681899065.923042 [0 127.0.0.1:64652] "LPUSH" "test_queue" "1st will not come" <-- Redis responds to the command that has timed out
1681899065.923135 [0 127.0.0.1:64651] "BRPOP" "test_queue" "0"
1681899065.931756 [0 127.0.0.1:64652] "LPUSH" "test_queue" "2nd will come"
1681899065.935937 [0 127.0.0.1:64651] "BRPOP" "test_queue" "0"
1681899065.935977 [0 127.0.0.1:64652] "LPUSH" "test_queue" "3nd will come"
1681899065.941560 [0 127.0.0.1:64651] "BRPOP" "test_queue" "0"
```

If you have that kind of use-case, please use either a reasonable timeout at `BRPOP` or configure `TimeoutSource` accordingly.

**Comment by giridharkannan** [comment]
There is a difference. Please do check the Wireshark packets, you would find that BRPOP was registered back before the first LPUSH, yet we missed receiving the response
