### ISSUE TITLE
How to get slots which are in importing/migrating state

### ISSUE THREAD

**Issue by SreedharReddyKallu** [lettuce-io/lettuce-core#2359]
### Discussed in https://github.com/lettuce-io/lettuce-core/discussions/2317

<div type='discussions-op-text'>

<sup>Originally posted by **SreedharReddyKallu** February  6, 2023</sup>
cluster nodes command shows slots which are in importing/migrating state through (->- NodeId/ -<-NodeId). Is there a way to retrieve this info using lettuce apis?</div>

**Comment by SreedharReddyKallu** [comment]
Seems like while parsing transition slots info is ignored.
https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/cluster/models/partitions/ClusterPartitionParser.java#L279

**Comment by mp911de** [comment]
Our parser indeed ignores slots in transition because these aren't helpful for our operations. We rather rely on the Redis state that updates much more frequently than our topology updates. 
You will need to parse the topology either yourself or use different Redis commands such as `CLUSTER SHARDS`.
