### ISSUE TITLE
Update `RedisVersion` parser to accept version numbers with non-numeric suffix

### ISSUE THREAD

**Issue by devkanro** [lettuce-io/lettuce-core#2557]
#### Current Behavior

Cloud providers may provide private fixes for Redis, causing their bugfix versions to be somewhat different, which causes link failure after upgrading to Lettuce 6.3.0.

Lettuce should not assume that bugfix version is a standard number.

https://github.com/lettuce-io/lettuce-core/blob/bc4aa0658ac73c496e6006cdf0680e602cb35945/src/main/java/io/lettuce/core/RedisHandshake.java#L337

#### Environment

- Lettuce version(s): 6.3.0.RELEASE,
- Redis version: 6.8.26(Baidu Release)

#### Possible Solution

Just try parse the bugfix version as int, provide a default value(0) for failed parsing.

**Comment by mp911de** [comment]
OMG. 

> Lettuce should not assume that bugfix version is a standard number.

Probably stating the obvious, but messing with version numbers that are otherwise all numbers is asking for trouble.

Using Regex seems the better approach for here. Do you want to submit a pull request?

For the time being, please use RESP2 as workaround to avoid the code path that parses the Redis version.

**Comment by devkanro** [comment]
@mp911de PR created #2558
