### ISSUE TITLE
Document how SCAN is supposed to be used

### ISSUE THREAD

**Issue by jacek99** [lettuce-io/lettuce-core#497]
I am trying to use scan() and it is returning zero keys for me every time, even though the equivalent command in Redis itself returns results.

Could you please document how scan() should be properly coded with ScanArgs, ScanCursor, etc?

It's not very clear, since I presume the ScanCursor from the last query needs to be reused for the subsequent one, etc.

**Comment by jacek99** [comment]
I am trying to use it with a KeyStreamingChannel and then from within the callback doing a secondary query to get the actual value of the key being streamed. Not sure at all if that is the most efficient.

**Comment by jacek99** [comment]
The code I have is 

```
            ScanCursor cursor = ScanCursor.INITIAL;
            while (!cursor.isFinished()){

                RedisFuture<StreamScanCursor> future = redis.async.scan(new KeyStreamingChannel<String>() {
                        @Override
                        public void onKey(String key) {
                            try {
                                Map<String,byte[]> data = redis.async(ctx).hgetall(key).get();
                                // ... do stuf with the data....  
                            } catch (Exception e) {
                                log.error("Redis operation failed",  e);
                            }
                        }
                    }, cursor, args);

                log.info("Waiting for next SCAN cursor");
                cursor = future.get();
            }
```

It just hangs there on the future.get() and just seems to wait.
The last line in my logs is the "Waiting for next SCAN cursor"

**Comment by mp911de** [comment]
@jacek99 – thanks for filing a ticket.

The [tests](https://github.com/lettuce-io/lettuce-core/blob/22a37ab9b9f9c33195e99b37d12da333713f9a5b/src/test/java/com/lambdaworks/redis/commands/KeyCommandTest.java#L384) give a pretty good impression how to use the API, that's why I haven't provided a guide. In general, your approach is correct but you're blocking the event loop that's why your code does not complete. Subsequent calls to `scan(…)` require the previously obtained cursor.

Blocking calls (`Future.get()`, `Future.await()`) inside of future/result callbacks (such as `KeyStreamingChannel.onKey(…)`) prevent the netty I/O thread from progressing. You have multiple options from here on:

1. Propagate the asynchronous flow: Don't call `.get()` but rather chain futures if you're using the asynchronous API (`.thenApply(…)`, `.thenAccept(…)`).
2. Don't use the async API and switch to synchronous processing:

Using `ScanIterator`:

```java
ScanIterator<String> scan = ScanIterator.scan(connection, ScanArgs.Builder.limit(50).match("key-foo"));
        
while (scan.hasNext()) {
    String next = scan.next();
    
}
```

Synchronous `scan` use:

```java
KeyScanCursor<String> cursor = redis.scan(ScanArgs.Builder.limit(50).match("key-foo"));

while (!cursor.isFinished()) {
    cursor = redis.scan(cursor);
}
```

Using small block sizes ( ~ 50 items) works on average pretty well because a network read spans about 1kB and if your key size does not exceed 20 bytes on average then all data is read within a single I/O operation. I'm going down the synchronous route because asynchronous programming comes at a certain complexity. Async does not necessarily reduce latency but increases the probability of bugs and unwanted concurrency issues.

**Comment by mp911de** [comment]
No further communication indicates the question has been answered, so closing this ticket.

**Comment by markthegrea** [comment]
I have tried the above code and have not gotten the expected results.

When I run this code I get 816 different keys that start with 'device'
```
List<String> keys = redisConnection.sync().keys("device*");
int index = 1;
for (String key : keys) {
	String value = redisConnection.sync().get(key);
	System.out.println(index + ". " + key + " - " + value);
	index++;
}
```
example output:
808. device|a5:n2|AUTOA175FF2Z00031 - somejson
809. device|pl3xx|MIDTGF00610 - someotherjson.

However, when i run this code:

```
KeyScanCursor<String> cursor = redisConnection.sync().scan(ScanArgs.Builder.limit(50).match("device*"));
List<String> keys = new ArrayList<String>();
while (!cursor.isFinished()) {
	keys.addAll(cursor.getKeys());
	System.out.println(keys.size());
	cursor = redisConnection.sync().scan(cursor);
}
```

The list never stops and i get keys that do not match "device*".  The first grab gets one
item that does start with "device*" but the rest are other unwanted keys.

Any help?

**Comment by markthegrea** [comment]
I believe I figured it out and instead of deleting the previous post I think this might be worth documenting:

```
while (!cursor.isFinished()) {
			for (String key : cursor.getKeys()) {
				String value = redisConnection.sync().get(key);
				System.out.println(index1 + ". " + key + " - " + value);
				index1++;
			}
			cursor = redis.scan(cursor, ScanArgs.Builder.limit(50).match("device*"));
		}
```
The code change adding the scanArgs to the inner call.  This was missing from the example above.

**Comment by mp911de** [comment]
Your code does not pick up the keys returned by the very last `scan(…)` call.

**Comment by torniketar** [comment]
@mp911de 
its quite old post but after lots of load on redis seems like my scan implementation is very slow and takes more time than expected, please take a look what i'm doing wrong or can i refactor it to speed up:

```
public Set<String> getAllScannedKeys(String key){
  	Set<String> result = new HashSet<>();  	
        ScanArgs args = new ScanArgs(); 	
        args.match(key); 	
       args.limit(DEFAULT_CURSOR_LIMIT);  
	KeyScanCursor<String> currentCursor = null;  	
        do {
 		if (currentCursor == null) { 	
		currentCursor = streamRedisTemplate.scan(args); 	
         	} else { 			
                 currentCursor = streamRedisTemplate.scan(currentCursor, args); 		} 		            result.addAll(currentCursor.getKeys());  	 }
           while (!currentCursor.isFinished());  	
          return result;
  }
```
streamRedisTemplate RedisAdvancedClusterCommands<String, String> type

**Comment by eraoul** [comment]
I still don't understand fully how to use the synchronous solution (as fixed up by markthegrea), since I don't see how to reset the cursor to "0" if I want to do another scan for different keys.  If I do another scan after this loop completes, the cursor is in a weird state.

**Comment by roottraveller** [comment]
which one should I use for the Redis cluster with over half a million keys ScanIterator<String> or KeyScanCursor<String>?
