### ISSUE TITLE
Pipeline performances

### ISSUE THREAD

**Issue by varknull** [lettuce-io/lettuce-core#502]
Hello,
this is more a question on how to get the best performance for a GET redis pipeline. In my scenario, I use one single connection shared across multiple threads (request handled by netty) and this piece of code that does 3 GET for every request from a redis server:

```
RedisAsyncCommands<String, String> commands = connection.async();
commands.setAutoFlushCommands(false);

List<RedisFuture<String>> futures = Lists.newArrayList();

RedisFuture<String> userFuture = commands.get(prefix + userId);
futures.add(userFuture);
RedisFuture<String> utFuture = commands.get(getUserTagKey(prefix, userId, tagId));
futures.add(utFuture);
RedisFuture<String> tagFuture = commands.get(prefix + tagId);
futures.add(tagFuture);

commands.setAutoFlushCommands(true);
commands.flushCommands();

// wait until all futures complete
boolean result = LettuceFutures.awaitAll(100, TimeUnit.MILLISECONDS, futures.toArray(new RedisFuture[futures.size()]));

if (result) {
    history.setUserHistory(deserializeUserHistory(userFuture.get()));
    history.setUserTagHistory(deserializeUserTagHistory(utFuture.get()));
    history.setTagHistory(deserializeTagHistory(tagFuture.get()));
}
```

I tried different solutions with lettuce (consumer future listener, connection pool, reactive api) but the overall performances are lower (according to my wrk measures) than the synchronous jedis approach. I would have expected similar results so I'm wondering if I'm misusing something or if there is a way to do better. Any suggestion will be appreciated.

By the way, I'm using lettuce version 4.3.1

**Comment by mp911de** [comment]
Hi, 
if you share the connection across multiple threads, then you should refrain from using `setAutoFlushCommands(…)` because `setAutoFlushCommands(…)` changes the state on connection-level that is visible to all other threads.

If you're not using Redis Cluster, then `MGET` might be the right choice for you. Lettuce is a bit slower than netty because it comes with more overhead (Each command creates a message object 
 that leads to a higher memory profile, command queueing for auto-reconnect and command replay after reconnect).

**Comment by varknull** [comment]
Thanks Mark, I see better performances by following your suggestions.

**Comment by mp911de** [comment]
May I close this ticket or is there anything else I can assist you with?

**Comment by varknull** [comment]
yes, thanks
