### ISSUE TITLE
Close connection

### ISSUE THREAD

**Issue by 0xbaadf00d** [lettuce-io/lettuce-core#530]
Hello,

I come  from Jedis, Is in Lettuce I have to close sync or async connections manually too (or using try / finally block) ?

**Comment by mp911de** [comment]
Lettuce connections are instances of `StatefulRedisConnection`. This API gives you access to execution-specific interfaces (sync/async/reactive). The only thing to close is the `StatefulRedisConnection`. Instances of sync/async/reactive interfaces depend on the `StatefulRedisConnection` and should not be closed. 

These interfaces implement `Closeable` because in earlier versions (Lettuce 2+3) connections were bound to the execution model. Sync and async execution required two connections and that changed in Lettuce 4.

In general, Lettuce connections are threadsafe. Unless you're using blocking commands (`BLPOP`, `BRPOP`) or transactions (`MULTI`/`EXEC`), a single connection yields the best performance.
