### ISSUE TITLE
No longer able to append to List returned by lrange (and possibly other commands)

### ISSUE THREAD

**Issue by andrewsensus** [lettuce-io/lettuce-core#587]
version: 4.4.0.Final
what I'm trying to do -- get a list from redis, append something to it, then hand it off for additional processing as in the following
```
RedisCommands<String, byte[]> sync = redisConnection.sync();
// ...
public List<byte[]> getPackets( /* ... */) {
// ...
return sync.lrange(key, 0, -1);
}
// ...
List<byte[]> myList = getPackets( /*...*/ );
// ...
myList.add( /* ... */ ); // throws java.lang.UnsupportedOperationException under 4.4.0.Final
// works under 4.0.Final (and based on timing of 9691d2a / #573
// I expect also under 4.3.0.Final, although I've only tested 4.4.0.Final and 4.0.Final.
```

Collections.emptyList() is being returned now and wasn't before.

I can work around this by finding every caller of lrange (and possibly other list-returning operations) and either:
1. unconditionally copying the returned list into a new list or
2. checking for the empty list and returning a new, mutable, empty list instead

Either of these are extra steps which make using the library harder and at least partially negate the performance gain of #573 

Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/master/.github/CONTRIBUTING.md).
- [x] You specify the lettuce version and environment so it's obvious which version is affected
- [x] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

**Comment by andrewsensus** [comment]
additional environment info: tested on both Linux and Windows, running against:
```
    <dependency>
      <groupId>com.github.kstyrc</groupId>
      <artifactId>embedded-redis</artifactId>
      <version>0.6</version>
    </dependency>
```

**Comment by mp911de** [comment]
Thanks for this ticket. The related change is #573 where we introduced lazily allocated collections. All collection-like output are initialized with `Collections.empty(List|Set)()` to reduce allocations if an Array-Response is empty. 

Changing returned collections is an anti-pattern because you can't oversee what else is affected by altering a returned collection. If you need to work with the data in a modifying way, then create a new collection `List<byte[]> myList = new ArrayList<>(getPackets( /*...*/ ));`.
