### ISSUE TITLE
Why does the reactive API not return Collections but rather emits single elements?

### ISSUE THREAD

**Issue by moores-expedia** [lettuce-io/lettuce-core#609]
This is a question about the consistency between Rx Set, synchronous, and hash API consistency.
Using version: 4.4.0.Final.

I'm using the Rx interfaces, calling hgetall and smembers.  I'm having an issue with Rx smembers (`rx.Observable<V> smembers(K key)`) because it does not return a `Set` (whereas the synchronous version does).  Rx `hgetall` (`rx.Observable<Map<K,V>> hgetall(K key)`) works fine becuase it returns a `Map`.   I'm using a `ByteArrayCodec`, and when flatmapping the output of `smembers` I get a byte array when I think I should be getting back a `Set`.
Can you tell me why the `RedisSetReactiveCommands<K, V>` API was designed this way?

**Comment by mp911de** [comment]
The reactive API renders all Redis array responses as single elements. In the imperative API, these command responses map to a `Collection` type such as `Set` or `List`. Collection types are natural to imperative APIs. Reactive APIs follow a streaming notion: An `Observable<T>` allows element-wise emission and solves two issues:

1. You're no longer required to await the last element of the stream to start processing the first emitted element
2. Array responses are not backed by a `List` or array hence there are no references kept by any utility data structure which allows a faster GC disposal (unless you collect these elements). Wrapping elements in a `List` (or similar) within the imperative API is a limiting constraint when working with data sets that easily could exhaust your JVM memory.

There are a few more aspects that play into Lettuce's API design: 

* With a collection returned from a Redis Set, it does not really matter whether the elements are represented within a `List` or a `Set` because Redis itself takes care of the underlying data structure properties.
* A collection of elements is either used to process each element or used within its `Collection` container because some API accepts it as `List`, `Set`, …. The reactive API facilitates the first case while you can still collect all elements to a `List` (`Observable.toList()`) if you wish to do so

You mentioned another method: `rx.Observable<Map<K,V>> hgetall(K key)`

There's a difference between the methods returning `Map`-like responses and array responses. The alternative return types for these kinds of methods could be either `rx.Observable<Map.Entry<K,V>>` or `rx.Observable<KeyValue<K,V>>`. Usage of a `Map`-like data structure is fundamentally different than a `Collection`-like data structure. With maps, one either uses `Map` lookup by key or processes entries to map these to an object or such. Collecting elements to a `Map` requires RxJava users to construct at least one `Func1` to map keys and values and therefore collection to `Map` is rather complex.

Therefore, we decided to accept the limitation of `Map` collection by our API and reduce complexity on in the client code.

Does this make sense? We're happy to get feedback and discuss how we can improve the driver.

**Comment by moores-expedia** [comment]
Thanks for the explanation. I understand the reasoning for the differentiation between maps and collections now.
