### ISSUE TITLE
RedisAdvancedClusterAsyncCommands does not include transactional commands

### ISSUE THREAD

**Issue by ryandbair** [lettuce-io/lettuce-core#618]
Rocking Lettuce 5.0.0 here.

The transactional commands are not included in the RedisAdvancedClusterAsyncCommands interface but are included in the corresponding class, RedisAdvancedClusterAsyncCommandsImpl. 

I believe RedisClusterAsyncCommands should extend RedisTransactionalAsyncCommands.

**Comment by mp911de** [comment]
Thanks for raising this issue. Transactional commands are not included in `RedisAdvancedClusterAsyncCommands` by design. Transactions are not possible in Redis Cluster from a cluster perspective. Transactions are only possible from a node perspective:

```java
StatefulRedisClusterConnection<String, String> connection = …;

StatefulRedisConnection<String, String> nodeConnection = connection.getConnection(host, port);

RedisAsyncCommands<String, String> async = nodeConnection.async();

async.multi();

// …

RedisFuture<TransactionResult> exec = async.exec();
```

It boils down to the absence of a distributed transaction notion in Redis.

References:

* [StackOverflow: Is there any Redis client (Java prefered) which supports transactions on Redis cluster?](https://stackoverflow.com/questions/42088324/is-there-any-redis-client-java-prefered-which-supports-transactions-on-redis-c/42091605#42091605)
* [Blog: Redis Transactions](https://paluch.biz/blog/161-redis-transactions.html)

**Comment by ryandbair** [comment]
Thanks, that makes sense given the design.
