### ISSUE TITLE
Can't solve a race condition with PubSub

### ISSUE THREAD

**Issue by philwo** [lettuce-io/lettuce-core#621]
Lettuce version: 5.0.0.RELEASE
Java version: OpenJDK 8
OS: Ubuntu 14.04 LTS
Redis 2.8.4 (from Ubuntu), also tested with 4.0.2.

This may well be a misunderstanding on my side (I'm not yet very used to reactive programming), but I can't seem to get a "blocking SMEMBERS" call working in Lettuce via PubSub. My call should return the results of SMEMBERS for a key if the key exists, otherwise subscribe via PubSub to the Keyspace Notifications and return the results once the key becomes available. Unfortunately, when the system is under load (lots of workers exercising that call and lots of keys being created by other workers), the Flux never completes, as all calls to membersWhenAvailable(key) will eventually hang. 

I'm including a minimal example of what I'm doing below. By adding a logging statement and trying the code in a playground tool and `redis-cli monitor`, I verified that the PubSub works in general.

```java
  private static final byte[] KEYSPACE_PREFIX = stringToBytes("__keyspace@0__:");

  // Initialized in the constructor.
  private final RedisClient client;
  private final StatefulRedisConnection<byte[], byte[]> conn;

  static class EmptyResult extends Throwable {
    static final EmptyResult INSTANCE = new EmptyResult();

    private EmptyResult() {
      super("empty result", null, true, false);
    }
  }

  public Flux<byte[]> membersWhenAvailable(byte[] key) {
    return Flux.create(
        (sink) -> {
          StatefulRedisPubSubConnection<byte[], byte[]> connection =
              client.connectPubSub(ByteArrayCodec.INSTANCE);
          sink.onDispose(() -> connection.close());
          RedisPubSubReactiveCommands<byte[], byte[]> reactive = connection.reactive();

          byte[] channel = concatByteArrays(KEYSPACE_PREFIX, key);
          reactive.subscribe(channel).subscribe();

          // In order to avoid a race condition where we run SMEMBERS, don't find any,
          // then subscribe via PubSub to changes, but miss changes that happened
          // between SMEMBERS and PubSub subscribe, we have to first subscribe,
          // then try the SMEMBERS call.
          Flux<ChannelMessage<byte[], byte[]>> channelWatcher = reactive
              .observeChannels()
              .cache(); // Not sure if this is needed.
          channelWatcher.subscribe(); // Not sure if this is needed.

          // Now that we're subscribed, fire off a SMEMBERS call that will also forward
          // to the sink. This will let this Flux complete immediately if there are
          // already existing items in the set.
          conn.reactive()
              .smembers(key)
              .switchIfEmpty(Flux.error(EmptyResult.INSTANCE))
              .retryWhen(companion -> channelWatcher)
              .subscribe(sink::next, sink::error, sink::complete);
        });
  }
```

The call is used by the worker like this:

```java
      Flux.concat(Flux.fromIterable(keysToProcess)
          .map(key -> redisConnection.membersWhenReady(key)
              .subscribeOn(Schedulers.elastic()))) // Not sure if this is needed.
          .blockLast();
```

When I add a `.mergeWith(Flux.interval(Duration.ofSeconds(1)))` to the retryWhen so that the SMEMBERS call is retried either when PubSub signals an event and on each second, it works fine.

Any idea what's going on here? I would be glad for any help. Thanks in advance.

**Comment by mp911de** [comment]
Thanks for filing an issue.
There are a few observations to be made:

1. You're connecting to Redis within the actual `Publisher` creation. Obtaining a connection is a blocking call that rather should happen outside the `Publisher` creation
2. You're subscribing to the channels first, then you're activating the listerner and events of the channel observation get lost. With `.cache()` you make sure to replay all events that were received until the actual `SMEMBERS` execution materializes.
3. Why are you subscribing on a scheduler (`subscribeOn(Schedulers.elastic())`)?

I think you could simplify your code a bit:

Somewhere in your initialization, before you start the actual worker:

```java
StatefulRedisPubSubConnection<byte[], byte[]> connection = …;
RedisPubSubReactiveCommands<byte[], byte[]> reactive = connection.reactive();
                    
Flux<ChannelMessage<byte[], byte[]>> keyspaceEvents = reactive.observeChannels().share();
Disposable subscribe = keyspaceEvents.subscribe(); // remember to dispose this one after you're done

connection.sync().subscribe(); // subscriptions are managed per connection, not per API flavour so subscribing synchronously is fine.
```

Then you should be able to reduce your code to

```java
Flux.merge(keyspaceEvents.filter(channelMessage -> …)
                         .take(1)
                         .flatMap(it -> reactive.smembers("key").collectList(),
                    reactive.smembers("key").collectList())
        .filter(it -> !it.isEmpty());
```

What this code does is, running `SMEMBERS` and returning it as list and start listening to the pub/sub event stream. If the event stream emits an item that qualifies as indicator that your set has been populated, it again runs `SMEMBERS` (that's up to you, whether you want to `SMEMBERS` again or you're happy with any list).

The significant bits here are:

1. Pick the first matching pub/sub event and terminate the stream from our perspective with `take(1)`
2. Filter out empty collections to hit the appropriate one

This approaches removes the gap that may happen due to non-atomic Redis commands, where things can happen in between and delays can suddenly make things work.

One last note: You don't need any schedulers because all I/O happens on netty threads. Stick to synchronous API usage when you're operating in a synchronous environment (initialization, application boot up) and use the reactive execution model if you can benefit from it.

**Comment by philwo** [comment]
Thanks for the detailed explanation, @mp911de!

I was able to solve the problem with your suggestion. :)
