### ISSUE TITLE
Question about pipelining

### ISSUE THREAD

**Issue by moores-expedia** [lettuce-io/lettuce-core#624]
I'm currently using 4.4.0.Final, as well as experimenting with your new 5.5.0 release.
I'm trying to port our Jedis based impl over to Lettuce.
I have a nice/clean RxJava1 implementation working, but the problem is that it does not look possible to control command flushing through RxJava.  I think this is why my Lettuce impl is much slower than my Jedis impl which uses the Jedis pipeline API extensively.  When running with DEBUG logging, I can see the flushing on every Observable.
I want to confirm that it's not possible to mingle RxJava Observables with explicit command flushing coordination.

We also noticed that Redis slows down when we try to create lots of connections to Redis.  
We use connection pools with Jedis because we have to.  We were thinking that going to Lettuce would allow us to use 1 connection or a much smaller pool of connections, with the assumption that connections can be shared across threads.  But if we take advantage of the asynchronous API and command batching, it looks like we also need pooling because the connection state must be managed per thread in order to pipeline.

Can you confirm these assumptions?

**Comment by mp911de** [comment]
You mentioned a couple of things here:

1. Flush-behavior: Lettuce writes by default each command to the transport and flushes immediately. You can control flushing (queue commands and write the whole queue at once) with [`StatefulRedisConnection.setAutoFlushCommands(boolean)`](https://github.com/lettuce-io/lettuce-core/wiki/Pipelining-and-command-flushing) and `StatefulRedisConnection.flushCommands()`. Lettuce applies pipelining for all commands that are dispatched. If you write multiple commands (e.g. using the async API), then all commands are sent to Redis directly without awaiting completion of the first command.

2. Lettuce is […] much slower than Jedis: Can you quantify your statement? Knowing how you actually use Lettuce would be helpful.

3. Command flushing using the reactive API: While it's possible to accumulate commands before they get written, complexity to control flushing increases with reactive execution by order of magnitude. Reactive execution mechanics defer the actual execution (queuing, write to the transport, response processing) once you start to materializing the actual reactive type (i.e., subscribing to the `Observable`). You need to hook into the right phase to flush commands and enable auto-flushing again. For Lettuce 4 (RxJava) flushing needs to happen after the subscription, for Lettuce 5 (Project Reactor), the flushing needs to happen after requesting the first chunk of data (`request(n)`) from the subscription.

4. Single connection vs. multiple connections: Since Redis is single-threaded, every user-space activity has to happen inside the single thread. Accepting/managing connections counts into user-space operations, too. Your observation is correct, the more connections/connects your Redis server has, the fewer operations you can perform. Decreasing the number of connections is a good measure to improve overall Redis performance.

5. Flushing-state and command buffers are managed per connection. You want to avoid shared mutable state that can harm your application. With Lettuce 5, you can write commands directly to a connection, either single commands or a [collection of commands](https://lettuce.io/core/release/api/io/lettuce/core/api/StatefulConnection.html#dispatch-java.util.Collection-). Dispatching commands from your application can quickly get you to the point of implementing own synchronization mechanisms. Lettuce 5 allows [micro-batching](https://github.com/lettuce-io/lettuce-core/wiki/Redis-Command-Interfaces#command-interfaces.batch) by using dynamic command interfaces. You might want to peek into that API. Micro-batching is managed per command interface instance and not per connection. It's a rather new API.

You might want to consider using netty directly along the Redis codec it provides.

**Comment by moores-expedia** [comment]
Thanks.

On item 2; I assumed that my Jedis impl is faster ONLY because I am pipelining with the Jedis driver and I'm not yet pipelining with the Lettuce reactive API.   

On item 3; It sounds like we should try out an asynchronous approach with RedisFuture, using the command interface, rather than diving into batching with reactive.

On item 5; I can batch commands through a single connection in a thread-safe way.  So microbatching through the command interface would allow me to avoid connection pooling.  
I have five logical chunks of work per client request to be executed in sequence, ideally five round trips to redis.  I could create five command interface based API calls that handle each step; but I might need to tune the micro batch size if steps require reading a "large" number of keys.   Does that sound right?

**Comment by mp911de** [comment]
> So microbatching through the command interface would allow me to avoid connection pooling.

exactly.

>  I could create five command interface based API calls

Yes. Depending on your commands, it could make sense to declare a scoped command interface that is dedicated to your Redis interaction:

```java
@BatchSize(50)
interface MyCommands extends Commands {

    RedisFuture<Set<String>> smembers(String key);

    RedisFuture<Map<String, String>> hmget(String key, String field);
}

MyCommands commands = …;

// batch is flushed after 50 calls to either one method
commands.smembers(…);
commands.hmget(…);
````
**Alternative: Specify batching behavior per invocation**

```java
interface MyCommands extends Commands {

    RedisFuture<Set<String>> smembers(String key, CommandBatching batching);

    RedisFuture<Map<String, String>> hmget(String key, String field, CommandBatching batching);
}

MyCommands commands = …;

// batch is flushed after 50 calls to either one method
commands.smembers(…, CommandBatching.queue());
commands.hmget(…, CommandBatching.flush());
```
**Alternative: or flush via BatchExecutor.flush() once all commands are queued**

```java
interface MyCommands extends Commands, BatchExecutor {

    RedisFuture<Set<String>> smembers(String key, CommandBatching batching);

    RedisFuture<Map<String, String>> hmget(String key, String field, CommandBatching batching);
}

commands.smembers(…, CommandBatching.queue());
commands.hmget(…, CommandBatching.queue());
commands.flush();
```

> It's not possible to execute several different redis commands in a single batch; ie one batch with an smembers and an hmget call.

It's not easily possible by using the connection-based control. It's easier to send a batch of two using command interfaces (see above, annotate your interface with `@BatchSize(2)`). Last possibility is custom command dispatching, see 5.

**Comment by mp911de** [comment]
Closing this question as the discussion continues on the [mailing list](https://groups.google.com/forum/#!topic/lettuce-redis-client-users/rF9pZ_1TAX0).
