### ISSUE TITLE
Question about Redis MGET with Lettuce Client

### ISSUE THREAD

**Issue by ahmednasir91** [lettuce-io/lettuce-core#630]
We have a use case where we want to fetch data in group - we first get the keys from an index which is a zset and based on that do a MGET to fetch rows. 
In some cases the MGET has around 5000+ keys - checking the slow logs we found lots of MGET with > 5k arguments. 
Any recommendations on what would be a better way to handle such cases? 
Does it have any negative impact on the redis CPU if this much keys are fetched in one call?

The payload size of value is around 4kb so if all 5000 keys are found then it will be 4kb * 5000.

**Comment by mp911de** [comment]
Thanks for your question. I'm not sure that's the right place for your question. Maybe the [Redis mailing list](https://groups.google.com/forum/#!forum/redis-db) is a better place for your question.

From my perspective: Passing a lot of keys to Redis creates a certain load in Redis: Your Redis server is blocked for a period of time because it handles your request. No other client is able to get a command done. Fetching keys in chunks doesn't get rid of the load but you split up the work so other clients would be able to get their commands processed. Chunking up a big list of keys into smaller ones also protects your application because you control the chunk size to not exhaust your memory.

Closing this one as I can't really answer the question properly from a Redis perspective.
