### ISSUE TITLE
There is no more shaded lettuce since 5.x.x ?

### ISSUE THREAD

**Issue by btd** [lettuce-io/lettuce-core#675]
Hi.

Thanks for great library. After using 5-6 different clients it is awesome.
Currently it is single depdency on netty in my project, but to add more i need to make sure they are not intersected or have the same version. I tried to look at maven and did not found any shaded jar http://central.maven.org/maven2/io/lettuce/lettuce-core/5.0.1.RELEASE/

Last one i see there http://central.maven.org/maven2/biz/paluch/redis/lettuce/4.4.2.Final/

Is this intentional?

**Comment by mp911de** [comment]
Yes, it's intentional to ship no shaded jar anymore (see #396). The shaded jar was introduced primarily because Lettuce 3 had much more dependencies (Guava, Netty 4.0 vs. 4.1). Things have changed right now and since the shaded jar caused lots of trouble in its maintenance, we decided to remove it.

We have [documented](https://github.com/lettuce-io/lettuce-core/wiki/Dependency-Compatibility-Matrix) netty compatibility if you need to pull in a different netty version.

**Comment by btd** [comment]
Thank you for answer, i noticed netty applied SemVer* so i should be safe with 4.1.X
