### ISSUE TITLE
Channel exceptions no longer propagated to RedisCommands

### ISSUE THREAD

**Issue by imasahiro** [lettuce-io/lettuce-core#707]
Hi, I'm using Lettuce 4.4.0-SNAPSHOT-c47b47464f6e22e005ad759782593773c8c1cd7c with NettyCustomizer (+ netty's [WriteTimeoutHandler](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/timeout/WriteTimeoutHandler.java))

When trying to upgrade to 4.4.3.Final, realize that we cannot get `WriteTimeoutException` from `redisCommands` when write timeout occur.
I just start to take a look at lettuce (and netty) code in detail. So I'm 100% not sure the root cause is in lettuce. But after do `git bisect` lettuce code with an unit test (https://github.com/imasahiro/lettuce-core/commit/00a8399f0f1ba4ff6e97e7acfec14aff85a9ae43) from 4.4.1.Final to current master, looks 8ebd52e8273885 commit change the behavior.
I cannot find any behavior change on channel pipeline but do you think the commit changes anythings?

Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/master/.github/CONTRIBUTING.md).
- [x] You specify the lettuce version and environment so it's obvious which version is affected
   - OK: 4.4.1.Final
   - NG: 4.4.2.Final ~ 4.4.3.Final
- [x] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.
   - https://github.com/imasahiro/lettuce-core/commit/00a8399f0f1ba4ff6e97e7acfec14aff85a9ae43

**Comment by mp911de** [comment]
Thanks for reporting an issue. To my understanding: You want `RedisCommand` to be completed exceptionally with netty's `WriteTimeoutException` if the write times out?

**Comment by mp911de** [comment]
The reason exceptions arrived in the command earlier was more by accident and because commands were added to the protocol stack (List of sent commands) before the actual write promise finished. 8ebd52e8273885cf09804e8608cabaa018afeabd changed the behavior to add commands to the stack only when the write completes.

This also means that commands written to a `Channel` are referenced by their future listener only ([`RetryListener`](https://github.com/lettuce-io/lettuce-core/blob/master/src/main/java/com/lambdaworks/redis/protocol/CommandHandler.java#L1348)) and not held anywhere else.

This change had some impact on the memory usage and how bounded queues behave.
The implementation of `WriteTimeoutHandler` isn't ideal. Lettuce uses pipelining which means that the head command in the stack isn't necessarily that one which failed. Or there could be multiple commands which failed but `exceptionCaught(…)` is a generic exception handler without any references to the promise that didn't complete in time.

It would make sense to propagate the timeout to the commands which are associated with the promise and complete only these.

**Comment by imasahiro** [comment]
> Thanks for reporting an issue. To my understanding: You want RedisCommand to be completed exceptionally with netty's WriteTimeoutException if the write times out?

Yeah, right.
And thanks for describing the change. It would make sense to me. Let me change our side. Thanks.
