### ISSUE TITLE
RedisAdvancedClusterAsyncCommands.scriptLoad tries to load script on failed nodes

### ISSUE THREAD

**Issue by kamran-rahmani** [lettuce-io/lettuce-core#720]
Hi,

I am using redis 4.0.8 and lettuce-core:5.0.2.RELEASE. I have a cluster of 3 masters and 3 slaves and use the following config to create RedisAdvancedClusterAsyncCommands through Spring Boot injection. 

```
ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder().enablePeriodicRefresh(Duration.ofSeconds(1))
                .build();

        SocketOptions socketOptions = SocketOptions.builder()
                .connectTimeout(Duration.ofSeconds(10))
                .keepAlive(true)
                .tcpNoDelay(false)
                .build();

        redisClusterClient.setOptions(ClusterClientOptions.builder()
                .topologyRefreshOptions(topologyRefreshOptions)
                .socketOptions(socketOptions)
                .build());
```
 
I have slave1 and slave2 as the seed nodes for the clusterClient creation. Before starting the application, I bring down slave 2, then I start the application, then I get the following exception when try to run any redis command:

```
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:7005, class java.util.concurrent.CompletionException, java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:7005
java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
io.lettuce.core.AbstractRedisClient.lambda$initializeChannelAsync$1(AbstractRedisClient.java:275)
io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:512)
io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:505)
io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:484)
io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:425)
io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:327)
io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:343)
io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
java.lang.Thread.run(Thread.java:748)
"&pod_name="unspecified_pod_name"`
```

It seems that lettuce is trying to connect to the dead slave node. I get the same issue when I have all the nodes running, bring up the application, and take down one of the masters. Lettuce still tries to connect to the dead master, although there is another slave being promoted to master instead. The only situation that works is when I take down the slaves after the application start up and also when I add new node to the cluster and migrate slots.

Is there any config that I am missing or is this a known issue? Thanks.

**Comment by mp911de** [comment]
I think I need a bit more context here. Where do you see this exception being thrown?

Bootstrapping a `RedisClusterClient` connection requires the topology to be loaded. `RedisClusterClient` attempts to connect to the seed nodes first, obtains the topology (via `CLUSTER NODES`), and eventually discovers the additional nodes from the response. Then, partition loading attempts to connect the nodes it received from `CLUSTER NODES` to get a full picture of the cluster. It may happen that some cluster nodes aren't available at that time which causes connect exceptions. This is a normal process and nothing to worry about.

During runtime, Lettuce attempts to connect the nodes for the purpose of reading. It opens connections to all read candidates. If nodes aren't reachable, then you can again see exceptions.

On a different note: Setting `enablePeriodicRefresh` to one second seems an overkill. Use at least 10 seconds and in production maybe even a higher value, otherwise you'll keep your cluster busy with connects.

**Comment by kamran-rahmani** [comment]
Thank you Mark for your quick response.  I found the issue and here is the summary:
Spring creates the RedisClusterClient and RedisAdvancedClusterAsyncCommands as part of the application startup. As part of the first request coming to our service, we load a lua script on all the redis nodes and then use the digest to eval queries. The problem I was facing was that if before starting my application, I bring down a node in the cluster, then start my service and make a request to it, it fails as it tries to connect to the node that is down. Turned out RedisAdvancedClusterAsyncCommands.scriptLoad was the reason where it doesn't honor the status of the nodes and tries to load the script on all the nodes (including the failed one). Also, thanks for your suggestion on the refresh interval. Yes, 1 sex is just for test, we plan to make it 10 second in production. We don't have that many nodes so it should be a fast refresh.

Thanks!

**Comment by mp911de** [comment]
Thanks a lot for all the details. `RedisAdvancedClusterAsyncCommands.scriptLoad(…)` behaves perfectly fine. It fails when the command wasn't able to execute properly on all nodes. This command distributes `SCRIPT LOAD` calls to all nodes so that you don't need to iterate over all nodes.

Node recovery and script execution is indeed an interesting topic. Running Redis Cluster with pre-cached Lua usage requires all your nodes to be initialized with that particular Lua script. This issue is easier to solve for Redis standalone: You attempt to execute the script, if it's not available, then you load it and the next time it's available again. For Redis Cluster with slaves, you get some dynamic into the calls as you can't be exactly sure which slave node you'll hit the next time.

I see following approaches how to address your issue:

1. Use events to initialize Redis Cluster nodes upon connecting (`ConnectedEvent`, `ConnectionActivatedEvent`): This approach can initialize a node multiple times when you have multiple application instances
2. Do the initialization on Redis-instance level during provisioning/recovery: Here you would have a watchdog or monitoring service (or a Redis start script) where you directly initialize the Redis node that is affected with a failure. You'd include some `redis-cli` within the actual Redis start script. Doesn't work if you use a hosted (Azure Redis, AWS ElastiCache) instance.
3. Add a netty `ChannelHandler` as last element in the bootstrap chain to initialize your Redis instance at `Channel` level. Quite low-level but maybe the most stable approach in terms of stability. This guarantees some execution order before user-space commands get executed.

**Comment by kamran-rahmani** [comment]
Thanks Mark, this is very helpful. As the last question, can you provide an example or link for option 1 please? Thanks.

**Comment by mp911de** [comment]
The code could look like this:

```java
RedisClusterClient client = RedisClusterClient.create(…);
StatefulRedisClusterConnection<String, String> connection = client.connect();

Disposable eventSubscription = client.getResources().eventBus().get()
        .filter(ConnectionActivatedEvent.class::isInstance)
        .cast(ConnectionActivatedEvent.class)
        .map(it -> it.remoteAddress())
        .filter(InetSocketAddress.class::isInstance)
        .cast(InetSocketAddress.class)
        .doOnNext(remote -> {

            // That's the interesting bit
            Optional<RedisClusterNode> connectedNode = client.getPartitions()
                                    .stream()
                                    .filter(node ->
            {
                String host = node.getUri().getHost();
                int port = node.getUri().getPort();

                if (remote.getPort() == port && (remote.getAddress().toString().equals(host) || remote
                        .getHostName().equals(host))) {
                    return true;
                }

                return false;
            }).findFirst();

            connectedNode.ifPresent(it -> connection.getConnection(it.getNodeId()).async().scriptLoad(…));
        }).subscribe();

// eventSubscription needs to be closed upon application shutdown.
```

See also https://github.com/lettuce-io/lettuce-core/wiki/Connection-Events for further details.

May I close this ticket or is there anything else I can assist you with?

**Comment by xuririse** [comment]
Hi, 
    Sorry to continue this issue. I met problem on the behavor of scritload that fails when the command wasn't able to execute properly on all nodes. 

    The user case  is below:
    a1. The program has some lua scripts in resource of my JAR
    a2. The program invokes scriptLoad command in order to upload the lua scripts and cache the hashes of lua scripts
    a3. With the hashes, the program can invoke evalsha command.
    a4. One excepion handler is done for evalsha when no script found error occurs: eval will invoked instead. 

    In general, it works well. The problem scenario:
    b1. stop the program
    b2. shutdown one node (either master or slave is ok) of redis cluster
    b3. start the program

    Since eval has performance issue, I would like to use evalsha at most time. In order to reach the target, I need to get hash first by scriptload command.  Then you can see that in the problem scenario, my program can not work.
     Suppose a normal scenaio that one slave node is down and needs some fix or any other jobs. The the client program can not work before the slave node back unless we drop it from the redis cluster. Or change the code to use eval instead of evalsha with pure performance only if a slave node does not work. 
       Is it more reasonable to fix scriptload to send scripts to all connected master node? like below:
       public RedisFuture<String> scriptLoad(V script) {

        Map<String, CompletableFuture<String>> executions = executeOnNodes(cmd -> cmd.scriptLoad(script),
                redisClusterNode -> redisClusterNode.is(MASTER) && redisClusterNode.isConnected());

        return MultiNodeExecution.lastOfAsync(executions);
    }

      This is my local fix to let the program work well.
      As I know , the redis does not persistent the scripts. So if the node restart, the script will lost. User case a4 is necessary. So it might be accepable if scriptload does not send to all nodes.

      Do you have any suggestion? thank a lot
