### ISSUE TITLE
Javadoc mentions Delay.exponential() is capped at 30 milliseconds

### ISSUE THREAD

**Issue by phxql** [lettuce-io/lettuce-core#799]
Hi,

the documentation says in https://github.com/lettuce-io/lettuce-core/wiki/Configuring-Client-resources on reconnect delay that the upper limit is by default 30 seconds. If i take a look at the implementation in Lettuce 4.4.4, (com.lambdaworks.redis.resource.Delay#exponential(), which is used by default), the upperbound is 30 **milli**seconds, not seconds.

**Comment by mp911de** [comment]
Thanks for filing an issue. I think there are two things here:

1. The Javadoc says the upper limit is 30 milliseconds as per https://github.com/lettuce-io/lettuce-core/blob/42c51e60201c5da3e3f1be379c2f81e29de86cae/src/main/java/com/lambdaworks/redis/resource/Delay.java#L113
2. The actual upper bound is 30 second (30000 milliseconds).

```
        Delay exponential = Delay.exponential();
        for (int i = 0; i < 32; i++) {
            System.out.println(exponential.createDelay(i));
        }
```

results in an output of:

```

0
1
2
4
8
16
32
64
128
256
512
1024
2048
4096
8192
16384
30000
30000
30000
30000
30000
30000
30000
30000
30000
30000
30000
30000
30000
30000
30000
30000
```

Out of curiosity, how did you come across this issue?

**Comment by phxql** [comment]
Ah yeah, you're right. Only the milliseconds in the Javadocs are wrong.

I tried to find the cause for a problem where the Logger for `com.lambdaworks.redis.protocol.ConnectionWatchdog` and `com.lambdaworks.redis.RedisClient` where spamming our logs on WARN when our redis sentinel went down. I assumed that would be due to the reconnection delay not doing exponential backoff and start digging in the code.

But if the exponential delay is indeed working correct, then the cause must be something else.

**Comment by mp911de** [comment]
The log message you're seeing originates from calling [`RedisClient.connectSentinel(…)`](https://github.com/lettuce-io/lettuce-core/blob/4.4.x/src/main/java/com/lambdaworks/redis/RedisClient.java#L791). Looking at the thread, I find it unfortunate to use the Lettuce worker pool for this kind of operation as the threads might interfere with each other. This is because `connectSentinel(…)` is a blocking method and this does not play well when using other threads than the `main` application thread.

**Comment by mp911de** [comment]
That's fixed now. Closing this ticket.

Feel free to file a new issue if you run into problems.
