### ISSUE TITLE
Shared Connection Bottleneck for Spring Boot Application

### ISSUE THREAD

**Issue by csavory** [lettuce-io/lettuce-core#835]
@mp911de per your request, i'm opening a reqest here to describe the behavior we are seeing with our Spring Boot application.

We recently upgraded to Spring Boot 2.0.3 and with that switched from using Jedis to Lettuce.  With Jedis, we hade a pool of 250 connections.  I have been trying to use a pool of LettuceConnections because I see significant thread blocking (using AppDynamics) on LettuceFutures.awaitOrCancel when i use just the sharedConnection.  

We are using:
Spring Boot 2.0.3
Spring Data Redis 2.0.8
Lettuce 5.0.4.RELEASE
Elasticache (Redis): 3.2.6

I'm running a LoadTest against our app using JMeter.  AppDynamics is telling me that when we get up in to the 500-700 VirtualUser Range, our app is making 400 calls to redis per second.  When I started Load Testing Lettuce, I started to see slower response times even at 20 virtual Users.  Then tried manually setting useSharedCache to false and added a pool of 250 connections.  I was able to see reasonable response times up to about 500 virtual users.  Everything goes really smoothly until we get up to that number of users and then i start seeing calls to Redis take anywhere from 500ms to 10000ms.  It always gets blocked on LettuceFutures.awaitOrCancel.  If switch back over to using Jedis, Redis calls are no longer a bottleneck and our database becomes the bottleneck.  

I'm not sure I understand what you are saying in this thread.  https://github.com/spring-projects/spring-boot/issues/14196#issuecomment-416489631

> increasing the connection count for Redis Standalone does not improve throughput performance

On this page, https://redis.io/topics/benchmarks, it says 

> To really test Redis, you need multiple connections 
Even the Redis benchmark test creates multiple connections to the server. 

> With high-end configurations, the number of client connections is also an important factor

**Comment by mp911de** [comment]
Thanks for raising this issue.

`LettuceFutures.awaitOrCancel(…)` is a facility to await command completion. It compares quite well to what `SocketInputStream.read(…)` does: Awaiting until a response is available to be read (processed). This means that `awaitOrCancel` gets the most blame for time consumption as invocations spend the most time there waiting until a command is ready.

Lettuce works differently than Jedis: Jedis is not thread-safe which requires connection pooling for multi-threaded usage. Each thread uses its own connection. A single connection can only be used by a single thread otherwise, the protocol gets messed up. This also means that a thread must await command completion before a next command can be sent. Using pipelining requires a different API.

Lettuce is thread-safe and a single connection can be used by multiple threads. Commands are written immediately to the transport without awaiting completion of a previous command. Lettuce uses pipelining as the mode of operation. From that perspective, it does not really matter, whether you run on a single connection or multiple ones.

What puzzles me is the increase in latency. Does this also happen if you use Lettuce with connection pooling and disable connection sharing? Did you run a profiler to identify hotspots in computing (`LettuceFutures.awaitOrCancel` gets all the blame, the real cost comes from a different place)?

You might want to enable [Command latency metrics](https://github.com/lettuce-io/lettuce-core/wiki/Command-Latency-Metrics) that gives you insights about command latencies.

Happy to support you on the investigation and to fix issues that get visible on high throughput.

**Comment by csavory** [comment]
I actually ran into a bunch of these Async questions when I was doing my initial investigation about a month ago.  From what I can tell, we are using the Synchronous API, and not Asynchronous.  Whenever I put breakpoints inside LettuceConnection, only the sync() methods are called. I actually wanted to do a load test using Pipelining, but I can't get to work with Spring Data.  I posted this question on SO about a month ago. https://stackoverflow.com/questions/51756470/how-do-i-use-lettuce-async-connection-with-spring-cache-abstraction-rediscachem

If I can get Pipelining setup correclty I'd be happy to run another load test with our app and Lettuce set up.

**Comment by mp911de** [comment]
Okay, using Spring Data's `RedisCache` uses only the synchronous API and it's not able to utilize pipelining.

You can use pipelining yourself with Spring Data's `RedisTemplate`, see the [docs](https://docs.spring.io/spring-data/redis/docs/current/reference/html/#pipeline) for further details.

**Comment by csavory** [comment]
So, if we do use ```RedisCache```,  because we are using the Spring cache abstraction, do you recommend setting ```shareNativeConnection``` to false and using a pool of LettuceConnections?

**Comment by mp911de** [comment]
No. I recommend an investigation of why you experience a slowdown in the first place.

**Comment by shunminli** [comment]
I also encountered this phenomenon，and I used lettuce pool to fix it.
I used Spring boot 2.0.4.RELEASE, lettuce 5.1.0.RELEASE.
I set shareNativeConnection by default (true).
```
    lettuce:
      pool:
        maxIdle: 5
        maxActive: 20
        maxWait: 10
```

**Comment by mp911de** [comment]
Any update on this ticket?

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by YashchenkoN** [comment]
A few days ago we started to face exactly the same problem - the performance of our application degrades significantly when it processes a huge amount of data. We use Spring's cache abstraction (particularly `@Cacheable` annotation) for caching of some records from the DB so these records are reused while processing without any additional calls to DB. Internally Spring uses `LettuceConnectionFactory` connected to a Redis Cluster of 2 nodes.

It turned out that the application works faster WITHOUT cache than when the cache is enabled. From traces, we see that the application wastes up to 40 seconds (depending on the load) just for retrieving information from the Redis! Most of the time is used for `io.lettuce.core.LettuceFutures:awaitOrCancel` like mentioned in a question https://stackoverflow.com/questions/51756470/how-do-i-use-lettuce-async-connection-with-spring-cache-abstraction-rediscachem. The Redis instance itself wasn't overloaded or smth else - its metrics show the CPU and memory in acceptable conditions.

In the past, everything was performing very well. The only thing that has changed since then is the amount of data that the application handles - it has increased somehow. Since the code related to the configuration of Spring Cache hasn't changed anyhow, the overall situation looks very weird for me.

I tried increasing a connection pool size, setting `shareNativeConnection` to `false` but none of these things helped. Performance still remains poor and we are trying to understand what can we do in order to mitigate this issue. Could anyone recommend or suggest anything, please?

**Comment by swyu** [comment]
Did you solve this problem？I ran into the same problem，how can i do?

**Comment by csavory** [comment]
We ended up having to switch back to Jedis

```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>io.lettuce</groupId>
                    <artifactId>lettuce-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
        </dependency>
```

**Comment by yuyijq** [comment]
@csavory @mp911de 
I ran into the same problem.
I think the reason is single thread bottleneck. Because the lettuce use netty, with netty one thread per connection, and this thread process all IO event, all redis codec works etc.
And the cloud redis service(elasticache) always expose single endpoint through proxy, so only one thread process our all redis command.
