### ISSUE TITLE
AutoFlushCommands,  connection pooling and performance

### ISSUE THREAD

**Issue by lujia-zhang** [lettuce-io/lettuce-core#910]
Hi, I noticed that there are some changes on pipeline usage wiki. According to current wiki, "The AutoFlushCommands state cannot be set on pooled connections by the lettuce connection pooling." Does that means we cannot use `GenericObjectPool` to manage a pool of connections that can be used for pipeline? If yes, how should we manage dedicated connections for pipeline usage? I was thinking using a pool will have better performance than just using `client.connect();` every time when we need a pipeline. Any thoughts on that? Thanks in advance!
PS: Based on my testing, for actual sync() time, lettuce is faster than Jedis. But for total time of a pipeline request (including getting connections, etc.), lettuce is around 200 - 500  milliseconds slower for batch commands, which I think might because not using connection pool. (we manage our own connection pool when using Jedis)

**Comment by mp911de** [comment]
Lettuce is about 10 to 20% slower than Jedis. This is because Jedis uses a plain old `SocketInputStream`/`SocketOutputStream` within the calling thread to read and write directly commands using the RESP protocol without intermediate infrastructure.

Lettuce uses an event-driven model and creates a handful of objects to enqueue, write and decode a command. Lettuce also uses a dedicated I/O thread to decouple I/O from the code that wants to invoke a Redis command. This execution model requires zero to two context switches (depending on the programming model). With a synchronous/imperative programming model, the Redis command is passed from the calling thread to the I/O thread and upon response, the data needs to be passed from the I/O thread to the calling thread.

Regarding `AutoFlushCommands`: Changing auto-flush isn't allowed because the pool can't validate the connection otherwise. Therefore, we're preventing calls to `setAutoFlush(…)`.

**Comment by lujia-zhang** [comment]
@mp911de Thanks for your explanation. Then what is the proper & optimized way to make use of pipeline with Lettuce wen qps is high?

**Comment by mp911de** [comment]
Lettuce uses pipelining as the mode of operation (it does not await command completion before sending another command). We run benchmarks with our CI jobs and on TravisCI a single application (single-threaded) yields between 6000 to 24000 Redis commands per second.

Here's the link to the full benchmark:

* Benchmark results: https://travis-ci.org/lettuce-io/lettuce-core/jobs/452315123
* Benchmark code: https://github.com/lettuce-io/lettuce-core/blob/8daec0b836c11fd81e1a60a0d499935132539f62/src/test/jmh/io/lettuce/core/RedisClientBenchmark.java
