### ISSUE TITLE
Cluster topology not refreshed on MOVED redirect

### ISSUE THREAD

**Issue by Bonczidai** [lettuce-io/lettuce-core#924]
Cluster topology not refreshed on MOVED redirect for node connection

```java
RedisClusterNode node = redisClusterConnection.getPartitions().getPartitionBySlot(SlotHash.getSlot(ID));
        StatefulRedisConnection<String, String> nodeConnection = redisClusterConnection.getConnection(node.getNodeId());
        RedisAsyncCommands<String, String> commands =  nodeConnection.async();
        commands.setAutoFlushCommands(false);

...
```

with automatic refresh enabled: ` ClusterTopologyRefreshOptions.builder().enablePeriodicRefresh(Duration.ofMinutes(10)).enableAllAdaptiveRefreshTriggers().build()`

when the cluster keys distribution changes (e.g. relocating a key from one node to another), lettuce is not refreshed automatically:

```console
 io.lettuce.core.RedisCommandExecutionException: MOVED 9670 ...
```

```xml
        <dependency>
            <groupId>io.lettuce</groupId>
            <artifactId>lettuce-core</artifactId>
            <version>5.0.4.RELEASE</version>
        </dependency>
```

- manual invocation of `io.lettuce.core.cluster.RedisClusterClient#reloadPartitions` solves the issue

**Shouldn't the cluster topology be refreshed automagically in this case?**

**Comment by mp911de** [comment]
A refresh task should be scheduled in that case. Can you enable debug logging for `io.lettuce.core.cluster.ClusterTopologyRefreshScheduler` to see what happens there? Logger `io.lettuce.core.protocol` will also show additional details but depending on the load this might be too much noise.

**Comment by Bonczidai** [comment]
There seems to be no useful info in those logs :(

Tracing back the code on the `io.lettuce.core.cluster.ClusterTopologyRefreshOptions.RefreshTrigger#MOVED_REDIRECT` const we get to [this point](https://github.com/lettuce-io/lettuce-core/blob/af1dcad1028da5b51c4296255a2bb145cb207836/src/main/java/io/lettuce/core/cluster/ClusterDistributionChannelWriter.java#L79) in the code which does a `command instanceof ClusterCommand` check but the actual type is `AsyncCommand` - I see no similar handling for `AsyncCommand` type

**Comment by mp911de** [comment]
I missed the fact that you're operating directly on a node connection. Typically, Lettuce calculates slot hashes and dispatches commands through the cluster connection which uses `ClusterDistributionChannelWriter`. We use the topology to route the command to an appropriate cluster node that handles the slot hash. 

The underlying assumption here is that commands are routed to the right host based on the command key (slot hash). When using node connections directly, we don't react to `MOVED` redirections at all as these are just plain connections without routing. We cannot tell whether `MOVED` happened because Redis Cluster was reconfigured or whether the key isn't handled by the cluster node at all.

That being said, we're doing the right thing by not issuing topology refresh. Direct interaction with cluster nodes comes with more power and requires the calling code to react to responses.

**Comment by zyfsuzy** [comment]
how to solves the issue, I find this bug in my project.
