### ISSUE TITLE
Flux that reads from a sorted set using zrangeWithScores, then makes another call to zscrore(), never completes

### ISSUE THREAD

**Issue by vkurland** [lettuce-io/lettuce-core#962]
#### Current Behavior

using lettuce 5.1.3.RELEASE

I have two sorted sets where keys (members) are the same but scores are different. I need to get a flux or a stream of tuples [member, score1, score2].  There are different ways to do this but I want to avoid accumulating intermediate items in memory because both sets can be big. 

My approach is to call zrangeWithScore() on the first set to get ScoredValue that carries the set member string and the score, then call flatMap() from which make zscore() call against the other set to pick up the second score. 

#### Input Code

- Java/Kotlin/Scala/Groovy/… or Repo link if applicable:

the test that illustrates this (and fails) can be found here:  
https://github.com/vkurland/ltb/blob/master/src/test/java/ltb/ZSetReactiveTest.java

in this test suite test1 succeeds and test2 fails.

the relevant part of the test case looks like this:

```java
  final Long count = commands.zrangeWithScores(set1, 0, -1)
                    .flatMap(sv -> {
                        final String member = sv.getValue();
                        return Mono.zip(commands.zscore(set2, member), Mono.just(sv));
                    })
                    .count()
                    .block(Duration.ofSeconds(2));
```

the call always times out in 2 sec and never generates any results. I have tried to add some .log() calls. It looks like it gets values from zrangeWithScores(), subscribes to the internal zscore() calls but then it just stops until time out kicks. At that point, I see a flood of cancel(). 

no errors appear if I add doOnError() either at the top level or inside of flatMap()

#### Expected behavior/code

the flatMap() should actually collect messages published by the internal publisher

#### Environment

- Lettuce version(s): 5.1.3.RELEASE
- Redis version: 4.0.11

Thank you!

**Comment by mp911de** [comment]
There play multiple things into the issue:

1. You're using a single Redis connection to process a stream of data while requesting additional data. A connection does only a single thing at a time. Issuing additional commands requires that the previous response is consumed.
2. Lettuce suspends reading from the transport if there is no demand from the current subscriber.
3. Things come together: `flatMap(…)` requests additional data as long as there is incoming data and there is sufficient demand. At a certain point in time, `flatMap(…)` has pre-fetched a sufficient number of items and awaits completion. Therefore, it suspends reading. Because of the `zrangeWithScores` command is not yet completed, the `zscore` commands are also pending and cannot contribute to complete what happened in `flatMap(…)`.

Things that you can do:

1. Use a different connection to eliminate the cycle
2. Increase `flatMap(…)` concurrency and prefetch arguments to buffer more data

**Comment by mp911de** [comment]
After reconsidering the scenario multiple times, it seems there isn't really something that we can do here. There are two competing subscriptions and we cannot favor the current command (i.e. resume reading) as we have no knowledge of the downstream subscriber. We also want to keep not consumed data outside the JVM to prevent memory issues.

Therefore, I'm closing this ticket for now. We will revisit this one once we found a good approach that can help to address the concern.
